### ISSUE TITLE
Build directory contains old version of eucllid.py

### ISSUE THREAD

**Issue by mkretlow** [makemate/euclid_package#2]
The build sub directory contains an old version of euclid.py, where the long types are not removed, which causes errors under Python 3. So when this package is installed for example by `pip install git+https://github.com/makemate/euclid_package.git` , pip installs (copies) this old buggy version from the build directory, at least on my system (Linux and virtualenv). The copy of euclid.py in build/ needs to be replaced with the latest version which resides in the root directory.

**Current workaround:** 
```
git clone https://github.com/makemate/euclid_package.git
cd euclid_package
python setup.py clean --all install
```

**Comment by makemate** [comment]
I've updated the euclid.py in build, it sould work now with `pip install`

**Comment by mkretlow** [comment]
Thanks. `pip install git+https://github.com/makemate/euclid_package.git ` works now. `pip install euclid` (i.e. pypi.org) still installs the old version. But I just noted that on pypi there is an euclid3 package which works as well (`pip install euclid3`).
